// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ValhallaVaultCyberAwareness.Data;

#nullable disable

namespace ValhallaVaultCyberAwareness.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240306201042_seedMoreData")]
    partial class seedMoreData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Domain.Models.AnswerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("answer");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit")
                        .HasColumnName("is_correct");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("question_id");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Ett legitimt försök från banken att skydda ditt konto",
                            IsCorrect = false,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Answer = "En informationsinsamling för en marknadsundersökning",
                            IsCorrect = false,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 3,
                            Answer = "Ett potentiellt telefonbedrägeri",
                            IsCorrect = true,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 4,
                            Answer = "En legitim begäran om hjälp från en person i nöd",
                            IsCorrect = false,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 5,
                            Answer = "Ett romansbedrägeri",
                            IsCorrect = true,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 6,
                            Answer = "En tillfällig ekonomisk svårighet",
                            IsCorrect = false,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 7,
                            Answer = "Genomföra omedelbar investering för att inte missa möjligheten",
                            IsCorrect = false,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 8,
                            Answer = "Investeringsbedrägeri",
                            IsCorrect = true,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 9,
                            Answer = "Begära mer information för att utföra en noggrann \"due diligence\"",
                            IsCorrect = false,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 10,
                            Answer = "Ett misstag av kreditkortsföretaget",
                            IsCorrect = false,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 11,
                            Answer = "Kreditkortsbedrägeri",
                            IsCorrect = true,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 12,
                            Answer = "Obehöriga köp av en familjemedlem",
                            IsCorrect = false,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 13,
                            Answer = "Utbildning i digital säkerhet för alla anställda",
                            IsCorrect = true,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 14,
                            Answer = "Installera en starkare brandvägg",
                            IsCorrect = false,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 15,
                            Answer = "Byta ut all IT-utrustning",
                            IsCorrect = false,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 16,
                            Answer = "Informera alla användare om sårbarheten och rekommendera temporära skyddsåtgärder",
                            IsCorrect = true,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 17,
                            Answer = "Ignorera problemet tills en patch kan utvecklas",
                            IsCorrect = false,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 18,
                            Answer = "Stänga ner tjänsten tillfälligt",
                            IsCorrect = false,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 19,
                            Answer = "En enskild hackare med ett personligt vendetta",
                            IsCorrect = false,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 20,
                            Answer = "En konkurrerande företagsentitet",
                            IsCorrect = false,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 21,
                            Answer = "Organiserade cyberbrottsliga grupper",
                            IsCorrect = true,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 22,
                            Answer = "Återgå till kontorsarbete",
                            IsCorrect = false,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 23,
                            Answer = "Införa striktare lösenordspolicyer och tvåfaktorsautentisering för fjärråtkomst",
                            IsCorrect = true,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 24,
                            Answer = "Förbjuda användning av personliga enheter för arbete",
                            IsCorrect = false,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 25,
                            Answer = "Phishing",
                            IsCorrect = false,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 26,
                            Answer = "Ransomware",
                            IsCorrect = true,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 27,
                            Answer = "Spyware",
                            IsCorrect = false,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 28,
                            Answer = "Spyware",
                            IsCorrect = false,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 29,
                            Answer = "Ransomware",
                            IsCorrect = true,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 30,
                            Answer = "Adware",
                            IsCorrect = false,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 31,
                            Answer = "Cyberkriminalitet",
                            IsCorrect = false,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 32,
                            Answer = "Cyberspionage",
                            IsCorrect = true,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 33,
                            Answer = "Cyberterrorism",
                            IsCorrect = false,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 34,
                            Answer = "Social ingenjörskonst",
                            IsCorrect = false,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 35,
                            Answer = "Massövervakning",
                            IsCorrect = false,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 36,
                            Answer = "Riktade cyberattacker",
                            IsCorrect = true,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 37,
                            Answer = "GDPR",
                            IsCorrect = false,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 38,
                            Answer = "Säkerhetsskyddslagen",
                            IsCorrect = true,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 39,
                            Answer = "IT-säkerhetslagen",
                            IsCorrect = false,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 40,
                            Answer = "Oberoende hackare",
                            IsCorrect = false,
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 41,
                            Answer = "Aktivistgrupper",
                            IsCorrect = false,
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 42,
                            Answer = "Statssponsrade hackers",
                            IsCorrect = true,
                            QuestionId = 14
                        });
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Domain.Models.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Att skydda sig mot bedrägerier"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cybersäkerhet för företag"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cyberspionage"
                        });
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Domain.Models.QuestionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("subcategory_id");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Question = "Du får ett oväntat telefonsamtal från någon som påstår sig vara från din bank. Personen ber dig bekräfta ditt kontonummer och lösenord för att \"säkerställa din kontos säkerhet\" efter en påstådd säkerhetsincident. Hur bör du tolka denna situation?",
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            Question = "Efter flera månader av daglig kommunikation med någon du träffade på en datingsida, börjar personen berätta om en plötslig finansiell kris och ber om din hjälp genom att överföra pengar. Vad indikerar detta mest sannolikt?",
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 3,
                            Question = "Du får ett e-postmeddelande/samtal om ett exklusivt erbjudande att investera i ett startup-företag som påstås ha en revolutionerande ny teknologi, med garantier om exceptionellt hög avkastning på mycket kort tid. Hur bör du förhålla dig till erbjudandet?",
                            SubCategoryId = 3
                        },
                        new
                        {
                            Id = 4,
                            Question = "Efter en online-shoppingrunda märker du oidentifierade transaktioner på ditt kreditkortsutdrag från företag du aldrig handlat från. Vad indikerar detta mest sannolikt?",
                            SubCategoryId = 4
                        },
                        new
                        {
                            Id = 5,
                            Question = "Inom företaget märker man att konfidentiella dokument regelbundet läcker ut till konkurrenter. Efter en intern granskning upptäcks det att en anställd omedvetet har installerat skadlig programvara genom att klicka på en länk i ett phishing-e-postmeddelande. Vilken åtgärd bör prioriteras för att förhindra framtida incidenter?",
                            SubCategoryId = 5
                        },
                        new
                        {
                            Id = 6,
                            Question = "Inom företaget upptäckts det en sårbarhet i vår programvara som kunde möjliggöra obehörig åtkomst till användardata. Företaget har inte omedelbart en lösning. Vilken är den mest lämpliga första åtgärden?",
                            SubCategoryId = 6
                        },
                        new
                        {
                            Id = 7,
                            Question = "Vårt företag blir måltavla för en DDoS-attack som överväldigar våra servrar och gör våra tjänster otillgängliga för kunder. Vilken typ av aktör är mest sannolikt ansvarig för denna typ av attack?",
                            SubCategoryId = 7
                        },
                        new
                        {
                            Id = 8,
                            Question = "Med övergången till distansarbete upptäcker vårt företag en ökning av säkerhetsincidenter, inklusive obehörig åtkomst till företagsdata. Vilken åtgärd bör företaget vidta för att adressera denna nya riskmiljö?",
                            SubCategoryId = 8
                        },
                        new
                        {
                            Id = 9,
                            Question = "Hälsovårdsmyndigheten utsätts för ett cyberangrepp som krypterar patientdata och kräver lösen för att återställa åtkomsten. Vilken typ av angrepp har de sannolikt blivit utsatta för?",
                            SubCategoryId = 9
                        },
                        new
                        {
                            Id = 10,
                            Question = "Det globala fraktbolaget Maersk blev offer för ett omfattande cyberangrepp som avsevärt störde deras verksamhet världen över. Vilken typ av malware var primärt ansvarig för denna incident?",
                            SubCategoryId = 10
                        },
                        new
                        {
                            Id = 11,
                            Question = "Regeringen upptäcker att känslig politisk kommunikation har läckt och misstänker elektronisk övervakning. Vilket fenomen beskriver bäst denna situation?",
                            SubCategoryId = 36
                        },
                        new
                        {
                            Id = 12,
                            Question = "Regeringen blir varse om en sofistikerad skadeprogramskampanj som utnyttjar Zero-day sårbarheter för att infiltrera deras nätverk och stjäla oerhört viktig data. Vilken metod för cyberspionage används sannolikt här?",
                            SubCategoryId = 37
                        },
                        new
                        {
                            Id = 13,
                            Question = "Regeringen i Sverige ökar sitt interna säkerhetsprotokoll för att skydda sig mot utländska underrättelsetjänsters infiltration. Vilken lagstiftning ger ramverket för detta skydd?",
                            SubCategoryId = 38
                        },
                        new
                        {
                            Id = 14,
                            Question = "Lunds universitet upptäcker att forskningsdata om ny teknologi har stulits. Undersökningar tyder på en välorganiserad grupp med kopplingar till en utländsk stat. Vilken typ av aktör ligger sannolikt bakom detta?",
                            SubCategoryId = 39
                        });
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Domain.Models.SegmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Segments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Del 1 - Att skydda sig mot bedrägerier"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Del 2 - Att skydda sig mot bedrägerier"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Del 3 - Att skydda sig mot bedrägerier"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Del 1 - Cybersäkerhet för företag"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "Del 2 - Cybersäkerhet för företag"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Name = "Del 3 - Cybersäkerhet för företag"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Name = "Del 4 - Cybersäkerhet för företag"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Name = "Del 1 - Cyberspionage"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Name = "Del 2 - Cyberspionage"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Name = "Del 3 - Cyberspionage"
                        });
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Domain.Models.SubCategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("SegmentId")
                        .HasColumnType("int")
                        .HasColumnName("segment_id");

                    b.HasKey("Id");

                    b.HasIndex("SegmentId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kreditkortsbedrägeri",
                            SegmentId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Romansbedrägeri",
                            SegmentId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Investeringsbedrägeri",
                            SegmentId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Telefonbedrägeri",
                            SegmentId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bedrägerier i hemmet",
                            SegmentId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Identitetsstöld",
                            SegmentId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Nätfiske och bluffmejl",
                            SegmentId = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "Investeringsbedrägeri på nätet",
                            SegmentId = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "Abonnemangsfällor och falska fakturor",
                            SegmentId = 3
                        },
                        new
                        {
                            Id = 10,
                            Name = "Ransomware",
                            SegmentId = 3
                        },
                        new
                        {
                            Id = 11,
                            Name = "Statistik och förhållningssätt",
                            SegmentId = 3
                        },
                        new
                        {
                            Id = 12,
                            Name = "Digital säkerhet på företag",
                            SegmentId = 4
                        },
                        new
                        {
                            Id = 13,
                            Name = "Risker och beredskap",
                            SegmentId = 4
                        },
                        new
                        {
                            Id = 14,
                            Name = "Aktörer inom cyberbrott",
                            SegmentId = 4
                        },
                        new
                        {
                            Id = 15,
                            Name = "Ökad digital närvaro och distansarbete",
                            SegmentId = 4
                        },
                        new
                        {
                            Id = 16,
                            Name = "Cyberangrepp mot känsliga sektorer",
                            SegmentId = 4
                        },
                        new
                        {
                            Id = 17,
                            Name = "Cyberrånet mot Mersk",
                            SegmentId = 4
                        },
                        new
                        {
                            Id = 18,
                            Name = "Social engineering",
                            SegmentId = 5
                        },
                        new
                        {
                            Id = 19,
                            Name = "Nätfiske och skräppost",
                            SegmentId = 5
                        },
                        new
                        {
                            Id = 20,
                            Name = "Vishing",
                            SegmentId = 5
                        },
                        new
                        {
                            Id = 21,
                            Name = "Varning för vishing",
                            SegmentId = 5
                        },
                        new
                        {
                            Id = 22,
                            Name = "Identifiera VD-mejl",
                            SegmentId = 5
                        },
                        new
                        {
                            Id = 23,
                            Name = "Öneangrepp och presentkortsbluffar",
                            SegmentId = 5
                        },
                        new
                        {
                            Id = 24,
                            Name = "Virus, maskar och trojaner",
                            SegmentId = 6
                        },
                        new
                        {
                            Id = 25,
                            Name = "Så kan det gå till",
                            SegmentId = 6
                        },
                        new
                        {
                            Id = 26,
                            Name = "Nätverksintrång",
                            SegmentId = 6
                        },
                        new
                        {
                            Id = 27,
                            Name = "Dataintrång",
                            SegmentId = 6
                        },
                        new
                        {
                            Id = 28,
                            Name = "Hackad!",
                            SegmentId = 6
                        },
                        new
                        {
                            Id = 29,
                            Name = "Vägarna in",
                            SegmentId = 6
                        },
                        new
                        {
                            Id = 30,
                            Name = "Utpressningsvirus",
                            SegmentId = 7
                        },
                        new
                        {
                            Id = 31,
                            Name = "Attacker mot servrar",
                            SegmentId = 7
                        },
                        new
                        {
                            Id = 32,
                            Name = "Cyberangrepp i Norden",
                            SegmentId = 7
                        },
                        new
                        {
                            Id = 33,
                            Name = "It-brottslingarnas verktyg",
                            SegmentId = 7
                        },
                        new
                        {
                            Id = 34,
                            Name = "Mirai, Wannacry och fallet Düsseldorf",
                            SegmentId = 7
                        },
                        new
                        {
                            Id = 35,
                            Name = "De sårbara molnen",
                            SegmentId = 7
                        },
                        new
                        {
                            Id = 36,
                            Name = "Allmänt om cyberspionage",
                            SegmentId = 8
                        },
                        new
                        {
                            Id = 37,
                            Name = "Metoder för cyberspionage",
                            SegmentId = 8
                        },
                        new
                        {
                            Id = 38,
                            Name = "Säkerhetsskyddslagen",
                            SegmentId = 8
                        },
                        new
                        {
                            Id = 39,
                            Name = "Cyberspionagets aktörer",
                            SegmentId = 8
                        },
                        new
                        {
                            Id = 40,
                            Name = "Värvningsförsök",
                            SegmentId = 9
                        },
                        new
                        {
                            Id = 41,
                            Name = "Affärsspionage",
                            SegmentId = 9
                        },
                        new
                        {
                            Id = 42,
                            Name = "Påverkanskampanjer",
                            SegmentId = 9
                        },
                        new
                        {
                            Id = 43,
                            Name = "Svensk underrättelsetjänst och cyberförsvar",
                            SegmentId = 10
                        },
                        new
                        {
                            Id = 44,
                            Name = "Signalspaning, informationssäkerhet och 5G",
                            SegmentId = 10
                        },
                        new
                        {
                            Id = 45,
                            Name = "Samverkan mot cyberspionage",
                            SegmentId = 10
                        });
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Domain.Models.UserAnswers", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.Property<int>("AnswerId")
                        .HasColumnType("int")
                        .HasColumnName("answer_id");

                    b.HasKey("UserId", "AnswerId");

                    b.HasIndex("AnswerId");

                    b.ToTable("UserAnswers");

                    b.HasData(
                        new
                        {
                            UserId = "e547fd1c-ec07-49e1-b2ce-0d326f467c01",
                            AnswerId = 2
                        },
                        new
                        {
                            UserId = "e547fd1c-ec07-49e1-b2ce-0d326f467c01",
                            AnswerId = 4
                        },
                        new
                        {
                            UserId = "e547fd1c-ec07-49e1-b2ce-0d326f467c01",
                            AnswerId = 8
                        },
                        new
                        {
                            UserId = "e547fd1c-ec07-49e1-b2ce-0d326f467c01",
                            AnswerId = 11
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ValhallaVaultCyberAwareness.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ValhallaVaultCyberAwareness.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ValhallaVaultCyberAwareness.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ValhallaVaultCyberAwareness.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Domain.Models.AnswerModel", b =>
                {
                    b.HasOne("ValhallaVaultCyberAwareness.Domain.Models.QuestionModel", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Domain.Models.QuestionModel", b =>
                {
                    b.HasOne("ValhallaVaultCyberAwareness.Domain.Models.SubCategoryModel", "SubCategory")
                        .WithMany("Questions")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Domain.Models.SegmentModel", b =>
                {
                    b.HasOne("ValhallaVaultCyberAwareness.Domain.Models.CategoryModel", "Category")
                        .WithMany("Segments")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Domain.Models.SubCategoryModel", b =>
                {
                    b.HasOne("ValhallaVaultCyberAwareness.Domain.Models.SegmentModel", "Segment")
                        .WithMany("SubCategories")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Domain.Models.UserAnswers", b =>
                {
                    b.HasOne("ValhallaVaultCyberAwareness.Domain.Models.AnswerModel", "Answer")
                        .WithMany("UserAnswers")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ValhallaVaultCyberAwareness.Data.ApplicationUser", "User")
                        .WithMany("UserAnswers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Data.ApplicationUser", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Domain.Models.AnswerModel", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Domain.Models.CategoryModel", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Domain.Models.QuestionModel", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Domain.Models.SegmentModel", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Domain.Models.SubCategoryModel", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
